name: Generate Snake Contribution Game

on:
  schedule:
    # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # Permite rodar manualmente

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    name: Generate Snake Game and Deploy
    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Gera animações com Platane/snk
      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: joaooliveira10
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-light.svg?palette=github-light
            dist/github-snake.gif?color_snake=#FFA500&color_dots=#d1e9ff,#91c9ff,#409eff,#2673e0,#1a56b8

      # Publica no branch output
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
